services:
  rabbitmq:
    image: rabbitmq:4.1.4-management@sha256:294b01e1796a8acede4619f32a1c394fae1f8021e57986ea01aad38dc2a4f502
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
  worker:
    build: .
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq/
    depends_on:
      rabbitmq: {condition: service_healthy}
